# Generated by Django 5.2.11 on 2026-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Длительность (часов)'),
        ),
        migrations.AddField(
            model_name='master',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='Цена (тг)'),
        ),
    ]
